config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "home#index"

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  get 'merchant/:id',  to: "profile#merchant", as: "merchant"
  get 'user/:id',      to: "profile#user",     as: "user"
  post 'merchant/:id/like', to: 'profile#like', as: 'like_merchant'
  get '/search',   to: "home#search",      as: :search
  get '/mobile_search', to: "home#mobile_search", as: :mobile_search
  get '/set_city', to: "home#set_city",    as: :set_city

  controller :static_page do
    get 'about', as: :about
    get 'terms', as: :terms
    get 'privacy', as: :privacy
  end

  resources :tickets do
    resources :groups do
      member do
        post :join_pay
      end
    end
    resources :orders
    member do
      post :like
      post :calc_price
    end
  end

  namespace :mine do
    resources :tickets do
      resources :group_prices
    end
    resource :wallet do
      post :recharge, :withdraw
    end

    get :profile, :edit_profile
    patch :profile, action: :update_profile

    resources :orders
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_ticket
  before_action :set_group, only: [:join_pay]
  before_action :authenticate_user!

  def new
    @group = @ticket.groups.new
  end

  def create
    @group = @ticket.groups.new group_params.merge(leader: current_user)
    if @group.save
      redirect_to @ticket, notice: 'Create group for ticket success'
    else
      render action: :new, error: 'Create group for ticket fail'
    end
  end

  def join_pay
    @group_user = @group.groups_users.create group_user_params_for_pay
  end

  private

  def set_ticket
    @ticket = Ticket.find params[:ticket_id]
  end

  def set_group
    @group = @ticket.groups.find params[:id]
  end

  def group_params
    params.require(:et_group).permit(:name, :deadline, :target_amount)
  end

  def group_user_params
    params.require(:groups_user).permit(:amount)
  end

  def group_user_params_for_pay
    group_user_params.merge(user: current_user, status: :paid)
  end
end

app/views/groups/join_pay.js.erb
<% if @group_user.persisted? %>
  $("#join-group-<%= @group.id %>").modal("hide");
<% else %>
  $("#join-error-<%= @group.id %>").text("<%= @group_user.errors.full_messages.join(",") %>").show();
<% end -%>

app/views/groups/new.html.erb
<div class="container" id="edit-profile">
  <h1>Create Group</h1>
  <hr/>

  <%= simple_form_for([@ticket, @group], url: ticket_groups_path,wrapper: :clean, html: {class: 'form-horizontal'}) do |f| %>
    <%= f.error_notification %>

    <div class="form-group">
      <div class="col-xs-offset- col-xs-10">
        <div class="form-inputs">
          <%= f.input :name %>
          <%= f.input :deadline, as: :string, input_html: { class: 'datetimepicker' } %>
          <%= f.input :target_amount %>
        </div>
        <%= f.button :submit %>
      </div>
    </div>
  <% end -%>
</div>