config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "home#index"

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  get 'merchant/:id',  to: "profile#merchant", as: "merchant"
  get 'user/:id',      to: "profile#user",     as: "user"
  post 'merchant/:id/like', to: 'profile#like', as: 'like_merchant'
  get '/search',   to: "home#search",      as: :search
  get '/mobile_search', to: "home#mobile_search", as: :mobile_search
  get '/set_city', to: "home#set_city",    as: :set_city

  controller :static_page do
    get 'about', as: :about
    get 'terms', as: :terms
    get 'privacy', as: :privacy
  end

  resources :tickets do
    resources :groups do
      member do
        post :join_pay
      end
    end
    resources :orders
    member do
      post :like
      post :calc_price
    end
  end

  namespace :mine do
    resources :tickets do
      resources :group_prices
    end
    resource :wallet do
      post :recharge, :withdraw
    end

    get :profile, :edit_profile
    patch :profile, action: :update_profile

    resources :orders
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  CITIES = ['Philadelphia', 'New York']

  priceable :oprice, :shipping, :flatten_price

  belongs_to :user
  belongs_to :category
  has_many :group_prices
  has_many :groups, class_name: 'EtGroup'
  has_many :votes, as: :votable
  has_many :orders
  has_one  :time_tag, class_name: 'TimeForTicketSearch', dependent: :destroy
  has_many :feature_tickets, dependent: :destroy

  mount_uploader :image, ImageUploader
  mount_uploader :sitting_map, SittingMapUploader

  validates :minimum_amount, :amount, :name, :start_at, :oprice, :city, :category_id,
               :shipping, presence: true
  validates :start_at, time_period: { scope: :end_at }, if: :end_at
  validates :oprice, numericality: {  greater_than: 0 }
  validates :shipping, numericality: { greater_than_or_equal_to: 0 }
  validates :city, inclusion: { in: CITIES }
  validates :desc, length: { maximum: 3000 }
  validates :student_discount, inclusion: { in: 0..100 }, allow_nil: true
  validates :minimum_amount, numericality: { greater_than_or_equal_to: 5 }

  accepts_nested_attributes_for :group_prices, allow_destroy: true

  after_save do
    if flatten_discount.present? and group_prices.count < 2
      group_price = GroupPrice.find_or_initialize_by(ticket_id: id)
      group_price.update(range_from: 0, range_to: 100000, discount: flatten_discount)
    end
  end

  scope :sorted, ->(sort_type) { sort_type == 'title_up' ? order(name: :asc) : order(name: :desc) }

  scope :search_by_count, ->(count) do
    count ||= 5
    joins(:group_prices)
    .where(':count BETWEEN group_prices.range_from AND group_prices.range_to', count: count)
  end

  scope :search_by_price_range, ->(price_from, price_to, count, is_student = false) do
    sql_student_discount = is_student ? 'tickets.student_discount' : '0'
    sql_price = "ROUND((100.0 - group_prices.discount - #{sql_student_discount}) / 100 * tickets.oprice_in_cents / 100, 2)"
    sql_price_from = price_from ? (sql_price + ' >= :price_from') : ''
    sql_price_to = price_to ? (sql_price + ' <= :price_to') : ''
    sql_and = (price_from and price_to) ? ' AND ' : ''

    search_by_count(count)
    .where(sql_price_from + sql_and + sql_price_to, price_from: price_from, price_to: price_to)
  end

  scope :search_by, ->(query) do
    joins(:category)
    .where('lower(tickets.name) like :query OR lower(tickets.desc) like :query OR lower(categories.name) like :query', query: "%#{query.downcase}%")
  end
  scope :by_city, ->(city) { where(city: city) }

  delegate :name, to: :category, prefix: true, allow_nil: true

  self.per_page = 6

  def oprice_to_currency
    ActionController::Base.helpers.number_to_currency( oprice )
  end

  def shipping_to_currency
    ActionController::Base.helpers.number_to_currency(shipping)
  end

  def image_url version = :original
    if version == :original
      image.try(:url) || 'default_pic.jpg'
    else
      image.try(version).try(:url) || 'default_pic.jpg'
    end
  end

  def self.top_deals
    last(6).reverse
  end

  attr_accessor :start_at_date, :start_at_time
  ransacker :start_at_date do
    Arel.sql('date(start_at)')
  end

  ransacker :start_at_time do
    Arel.sql('(start_at)::time')
  end

  def ranked_group_prices
    group_prices.order(range_from: :asc)
  end

  def ranked_groups
    groups.order(deadline: :asc)
  end

  def price_when(count, for_student = false)
    price = group_price_by(count).try(:price) || flat_price || oprice
    price = price * (100 - student_discount) / 100 if for_student
    price
  end

  def ticket_enough?(quantity)
    amount >= quantity
  end

  def time_parse
    TimeForTicketSearch.create_time_tag(self.id, self.start_at)
  end

  # TODO: move this to helper
  def time_range(type = :number)
    if type == :number
      if end_at
        "#{start_at.strftime('%m/%d/%Y')}<br>#{to_day_time(start_at)} - #{to_day_time(end_at)}".html_safe
      else
        "#{start_at.strftime('%m/%d/%Y')}<br>#{to_day_time(start_at)}".html_safe
      end
    elsif type == :word
      if end_at
        "#{start_at.strftime('%B %d, %Y')}<br>#{to_day_time(start_at)} - #{to_day_time(end_at)}".html_safe
      else
        "#{start_at.strftime('%B %d, %Y')}<br>#{to_day_time(start_at)}".html_safe
      end
    elsif type == :start
      "#{start_at.strftime('%m/%d/%Y')}<br>#{to_day_time(start_at)}".html_safe
    end
  end

  def to_day_time(date_time)
    date_time.strftime('%l:%M %p')
  end

  def sold
    self.orders.where(status: :paid).sum(:count)
  end

  def flat_price count = 5, for_student = false
    fp = (for_student ? group_price_for_student(count) : group_price_by(count).try(:price)) || oprice
  end

  def flat_discount count = 5, for_student = false
    (for_student ? flat_discount_for_student(count) : group_price_by(count).try(:discount)) || 0
  end

  def minus_purchased_quantity! purchase_quantity
    self.update!(amount: amount - purchase_quantity)
  end

  def merchant_name
    user.try(:name)
  end

  def category_name
    category.try(:name)
  end

  def is_flatten_price?
    flatten_price.present? && flatten_price.to_i != 0
  end

  def discount
    is_flatten_price? ? flatten_discount : group_prices.try(:last).try(:discount)
  end

  private
  def group_price_by count
    ranked_group_prices
    .where('range_from <= :count and (range_to >= :count or range_to is null)', count: count)
    .first
  end

  def group_price_for_student count
    oprice * (100 - flat_discount_for_student(count)) / 100
  end

  def flat_discount_for_student count
    if gp = group_price_by(count)
      gp.discount + student_discount
    else
      0
    end
  end
end

app/controllers/mine/group_prices_controller.rb
module Mine
  class GroupPricesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_ticket
    authorize_resource

    def new
      redirect_to root_path unless current_user.merchant?
    end

    def create
      @group_price = @ticket.group_prices.new(group_price_param)
      if @group_price.save
        redirect_to [:mine, @ticket], notice: 'Create Price Tier Success'
      else
        flash[:error] = @group_price.errors.full_messages.join(', ')
        render :new
      end
    end

    def destroy
      @group_price = GroupPrice.find(params[:id])
      @group_price.destroy
    end
 
    private

    def set_ticket
      @ticket = Ticket.find(params[:ticket_id])
    end

    def group_price_param
      params.require(:group_price).permit(:range_from, :range_to, :discount)
    end
  end
end

app/controllers/mine/orders_controller.rb
module Mine
  class OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_order, only: [:checkout, :show]
    authorize_resource

    def index
      if current_user.normal?
        @orders = current_user.orders.order(id: :desc).page(params[:page]).per_page(20)
      elsif !current_user.verification?
        render :text => "You need verification"
      elsif current_user.merchant?
        @orders = Order.merchant_orders(current_user.id).page(params[:page]).per_page(20)
      end
    end

    def show
    end
    
    def update
      #TODO: Deal with payment thing
    end

    private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:ticket_id, :count)
    end
    
  end
end

app/controllers/mine/tickets_controller.rb
module Mine
  class TicketsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_ticket, only: [:show, :edit, :update, :destroy]
    authorize_resource

    # GET /tickets
    def index
      @q = Ticket.ransack(params[:q])
      @tickets = @q.result.where(user_id: current_user.id).page(params[:page]).per_page(20)
    end

    # GET /tickets/1
    def show
    end

    # GET /tickets/new
    def new
      redirect_to user_session_path unless current_user && current_user.merchant?
      @ticket = Ticket.new
      @ticket.group_prices.build
    end

    # GET /tickets/1/edit
    def edit
    end

    # POST /tickets
    def create
      @ticket = current_user.tickets.new(ticket_params)
      if @ticket.save
        respond_to do |format|
          format.html { redirect_to [:mine, @ticket], notice: 'Ticket was successfully created.' }
          format.json { render json: @ticket }
        end
      else
        respond_to do |formant|
          format.html { render :new, notice: 'Faild to create new ticket, please try again.' }
          format.json { render json: { error_code: 0 } }
        end
      end
    rescue Exception => e
      @ticket = Ticket.new(ticket_params)
      flash[:error] = e.inspect
      render :new
    end

    # PATCH/PUT /tickets/1
    def update
      if @ticket.update(ticket_params)
        redirect_to [:mine, @ticket], notice: 'Ticket was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /tickets/1
    def destroy
      @ticket.destroy
      redirect_to mine_tickets_path, notice: 'Listing was successfully deleted.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = current_user.tickets.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      change_params_year_format params      
      params.require(:ticket).permit(
        :city,
        :category_id,
        :name,
        :desc, 
        :start_at,
        :end_at,
        :amount,
        :minimum_amount,
        :oprice,
        :flatten_discount,
        :flatten_price,
        :student_discount,
        :shipping,
        :will_call,
        :service_fee_waived,
        :image,
        :sitting_map,
        group_prices_attributes: [:range_from, :range_to, :price]
      )
    end

    def format_time time
      return "" if time.blank?
      time_ary = time.split("/")
      [time_ary[1], time_ary[0], time_ary[2]].join("/").try(:to_datetime).try(:to_s, :db)
    end

    def change_params_year_format params
      params[:ticket][:start_at] = format_time params[:ticket][:start_at]
      params[:ticket][:end_at] = format_time params[:ticket][:end_at]
      params
    end
  end

end

app/controllers/mine/wallets_controller.rb
module Mine
  class WalletsController < ApplicationController
    before_action :authenticate_user!
    authorize_resource class: false

    def show
    end

    def recharge
      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        card: params[:stripeToken]
      )

      @transaction = Transaction.new(dollar: transaction_param[:recharge],
                                     user: current_user,
                                     transaction_type: :recharge,
                                     token: params[:stripeToken],
                                     customer_id: customer.id)

      Stripe::Charge.create(
        customer: customer.id,
        amount: @transaction.dollar_in_cents,
        description: 'Recharge to GroupEt Account',
        currency: 'usd'
      )

      @transaction.status = :success
      @transaction.save!

      redirect_to mine_wallet_path, notice: 'Recharge Success'
    rescue Stripe::CardError => e
      redirect_to mine_wallet_path, error: e.message
    rescue ActiveRecord::RecordNotSaved
      redirect_to mine_wallet_path, error: @transaction.errors.full_messages.join(' ')
    end

    def withdraw
    end

    private

    def transaction_param
      params.permit!
    end
  end
end

app/controllers/mine_controller.rb
class MineController < ApplicationController
  before_action :authenticate_user!
  authorize_resource class: false

  def profile
    @favourite_tickets = current_user.favourites
  end

  def update_profile
    final_param = current_user.merchant? ? merchant_param : user_param

    if current_user.update(final_param)
      respond_to do |format|
        format.html { redirect_to action: :profile }
        format.mobile { redirect_to mine_edit_profile_path }
      end 
    else
      render :edit_profile
    end
  end
  
  def edit_profile
    if current_user.merchant?
      @merchant_info = current_user.merchant_info || MerchantInfo.new(user_id: current_user.id)
      @address = @merchant_info.address || @merchant_info.build_address
    else
      @user_info = current_user.user_info || UserInfo.new(user_id: current_user.id)
      @address = @user_info.address || @user_info.build_address
    end
  end

  private

  def merchant_param
    params.require(:user).permit(:name,
                                 :email,
                                 :avatar,
                                 merchant_info_attributes:
                                 [:latitude, :longitude,
                                  :category_id,
                                  :phone,
                                  :url,
                                  :workday_opening_time,
                                  :sat_opening_time,
                                  :sun_opening_time,
                                  :orgnization,
                                  :sales_email,
                                  :sales_phone,
                                  address_attributes: [:first,
                                                       :second,
                                                       :city,
                                                       :state,
                                                       :zipcode]
                                 ]
                               )
  end
  def user_param
    params.require(:user).permit(:name,
                                 :avatar,
                                 :email,
                                 user_info_attributes: [
                                   :zipcode,
                                   :phone,
                                   :group_name,
                                   :number_of_group_members,
                                   :university,
                                   :wallet_link,
                                   :billing_address,
                                   address_attributes: [:first,
                                                        :second,
                                                        :city,
                                                        :state,
                                                        :zipcode]
                                 ]
                                )
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket
  authorize_resource

  def show
    @order = Order.new
    @tickets_search = TicketsSearch.new

    respond_to do |format|
      format.html { render 'show.html.erb' }
      format.mobile { render 'show.mobile.slim' }
    end
  end

  def like
    ticket = Ticket.find(params[:id])
    if current_user.tickets_voted?(ticket)
      current_user.favourites.delete(ticket)
    else
      current_user.favourites << ticket
    end
    respond_to do |format|
      format.js
    end
  end

  #TODO need to refator
  def calc_price
    count = params[:count].to_i
    @valid = count > 0 && (@ticket.amount - count) >= 0
    @flat_price = @ticket.flat_price(count, current_user.try(:is_student))
    @total_price = (@flat_price * count).round(2)
    respond_to do |format|
      format.js
      format.mobile { render template: 'tickets/calc_price.js.erb' }
    end
  end

  private

  def set_ticket
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/mine/tickets_helper.rb
module Mine::TicketsHelper
  def title_sort_icon
    if @sort_by == 'title_down' 
      link_to mine_tickets_path(sort_by: :title_up) do
        content_tag(:span, nil, class: 'glyphicon glyphicon-chevron-down')
      end
    else
      link_to mine_tickets_path(sort_by: :title_down) do
        content_tag(:span, nil, class: 'glyphicon glyphicon-chevron-up')
      end
    end 
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def render_group_price(gp)
    "#{gp.range_from}-#{gp.range_to}: #{number_to_currency(gp.price)}"
  end
end

app/views/mine/tickets/_form.html.erb
<%= simple_form_for([:mine, @ticket], html: {class: 'form-horizontal', onkeypress:'return event.keyCode != 13;'}, wrapper: :clean) do |f| %>
  <%= f.input_field :city, collection: Ticket::CITIES, prompt: 'Please Select a City...' %>
  <%= f.association :category, prompt: 'Please Select a Genre...', label: false %>
  <%= f.input :name, placeholder: 'Title', label: false %>
  <%= f.input_field :desc, placeholder: 'Discription:' %>
  <p> &nbsp;&nbsp;<small>(3000 characters max.)</small> </p>

  <div class=row>
    <div class='col-xs-6'>
      <%= f.input_field :start_at, as: :string, placeholder: 'Start Time', id: 'datetimepicker', value: @ticket.start_at.try(:to_s) %>
    </div>
    <div class='col-xs-6'>
      <%= f.input_field :end_at, as: :string, placeholder: 'End Time', id: 'datetimepicker', value: @ticket.end_at.try(:to_s) %>
    </div>
  </div>

  <%= f.input :amount, as: :integer, label: false, placeholder: 'Total quantity of tickets' %>
  <%= f.input :minimum_amount, as: :string, label: false,  placeholder: 'Minimum tickets for purchase' %>

  <div class="input-group" style='margin-bottom: 10px;'>
    <span class="input-group-addon">$</span>
    <%= f.input_field :oprice, placeholder: "Original price per ticket", value: (@ticket.new_record? ? nil : @ticket.oprice) %>
  </div>

  <% if @ticket.new_record? %>
    <div class='row' id='price-tiers'>
      <input type="checkbox" id="show-flat-discount" />
      Set a flat discount here or set specific discounts for different ticket quantity tiers after upload
    </div>
    <script>
      $("#show-flat-discount").change(function(){
        $(".flat-discount").toggle();
        $("#ticket_flatten_discount").val("");
        $("#ticket_flatten_price").val("");
      })
    </script>
    <div class='row flat-discount' style="display: none;">
      <div class='col-xs-5'>
        <div class="input-group">
          <%= f.input_field :flatten_discount, as: :string, placeholder: "Flat Discount Ticket" %>
          <span class="input-group-addon">%</span>
        </div>
      </div>
      <div class='col-xs-2 center' style='padding-top:5px;'> or </div>
      <div class='col-xs-5'>
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <%= f.input_field :flatten_price, as: :string, placeholder: "Flat Price per Ticket", value: format_price(@ticket.flatten_price) %>
        </div>
      </div>
    </div>
  <% elsif @ticket.is_flatten_price? %>
    <div class='row flat-discount'>
      <div class='col-xs-5'>
        <div class="input-group">
          <%= f.input_field :flatten_discount, as: :string, placeholder: "Flat Discount Ticket" %>
          <span class="input-group-addon">%</span>
        </div>
      </div>
      <div class='col-xs-2 center' style='padding-top:5px;'> or </div>
      <div class='col-xs-5'>
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <%= f.input_field :flatten_price, as: :string, placeholder: "Flat Price per Ticket", value: format_price(@ticket.flatten_price) %>
        </div>
      </div>
    </div>
  <% end %>

  <div id='discount' class='row'>
    <div class='col-xs-3' id='additional_discount'>
      <span><input type='checkbox' id='has-student-discount'/></span>
      <span> Additional Discount for Students?</span>
    </div>
    <div class='col-xs-2 input-group' id='student-discount'>
      <%= f.input_field :student_discount, as: :string, disabled: true %>
      <span class="input-group-addon">%</span>
    </div>
  </div>

  <div class='row'>
		<div class='col-xs-2' style='padding-top:5px;'>
			<span>&nbsp;&nbsp;Shipping Fee</span>
		</div>
		<div class='col-xs-2 input-group' id='shipping-fee'>
      <span class="input-group-addon">$</span>
			<%= f.input_field :shipping, value: format_price(@ticket.shipping) %>
		</div>
  </div>

  <div class='row'>
    <div class='col-xs-3'>
      <input type='checkbox' id='free-shipping' />
      <label>Free Shipping</label>
    </div>
    <div class='col-xs-3'>
      <%= f.input :will_call, wrapper_html: { class: "choose" }, label: "Free Will Call Pick-up" %>
    </div>
    <div class="col-xs-3">
      <%= f.input :service_fee_waived, wrapper_html: { class: "choose" }, label: "service Fee Waived" %>
    </div>
  </div>
  
  <div class="row">
    <div class='col-xs-8'>
      &nbsp;&nbsp;Performace image(max 5 MB.This will appear in search results.)
      <%= image_tag(@ticket.image, height: '80') %>
    </div>
    <div class="col-xs-4" style='padding-top: 25px;'>
      <%= f.input_field :image, as: :file %>
    </div>
  </div>
  <div class="row">
    <div class='col-xs-8'>
      &nbsp;&nbsp;Seating Level
      <%= image_tag(@ticket.sitting_map, height: '80') %>
    </div>
    <div class="col-xs-4" style='padding-top: 25px;'>
      <%= f.input_field :sitting_map, as: :file %>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-4 col-xs-offset-4">
      <%= f.button :submit, 'UPLOAD TICKET LISTING' %>
    </div>
  </div>
<% end %>

app/views/mine/tickets/_group_price_fields.html.erb
<p class="feilds" style="display:none">
  <%= f.input_field :range_from, value: 5, as: :string %>
	<%= f.input_field :range_to, as: :string, :"data-max" => 12 %>	
	<%= f.input_field :price, as: :string %>
</p>

app/views/mine/tickets/_price_tier.html.erb
<div id="group-price-tiers" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h2 class="center yellow">Add group price for @ticket.name </h2>
      </div>
      <div class="modal-body">
        <%= render "price_tier_list" %>
        <%= render "price_tier_modal_form" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag "slider" %>

app/views/mine/tickets/_price_tier_list.html.erb
<table id="group-price-tiers-table" class="table table-striped table-bordered table-condensed">
	<thead>
	  <tr class="purple-back">
		 <th class="center">Count Range</th>
		 <th class="center">Price Per Ticket</th>
	  </tr>
  </thead>
	<tbody>
	</tbody>
</table>

app/views/mine/tickets/_price_tier_modal_form.html.erb
<%= simple_form_for [:mine, GroupPrice.new]  do |f| %>
  <%= f.input :range_from %>
  <%= f.input :range_to %>
  <%= f.input :discount %>
  <%= f.submit :add_price_tier %>
<% end %>

app/views/mine/tickets/_table.html.erb
<table class="table table-striped table-bordered table-condensed">
	<thead>
	  <tr class="purple-back">
		 <th>#</th>
		 <th class="center">Image</th>
     <th class="center"><%= sort_link @q, :name, "Title/Date" %></th>
     <th class="center"><%= sort_link @q, :created_at, "Date Listed" %></th>
		 <th class="center">Total Quantity</th>
		 <th class="center">Quantity Sold</th>
		 <th class="center">Price Per Ticket</th>
		 <th class="center">% Discount</th>
     <th class='center'>Show</th>
		 <th class="center">Edit</th>
		 <th class="center">Delete</th>
	  </tr>
  </thead>
  <% @tickets.each_with_index do |ticket, index| %>
    <tr>
      <td class="purple-back">
        <% if params[:page]  %>
          <%= (params[:page].to_i - 1 ) * 20 + index + 1 %>
        <% else  %>
          <%= index + 1%>
        <% end %>
      </td>
      <td><%= link_to (image_tag ticket.image_url(:thumb)), ticket, alt: ticket.name %></td>
      <td>
        <h3><%= link_to ticket.name, ticket_path(ticket) %></h3>
        <p><%= ticket.time_range(:word) %></p>
      </td>
      <td class="center" style="vertical-align: middle"><%= ticket.created_at.strftime("%m/%d/%Y")  %></td>
      <td class="center" style="vertical-align: middle"><%= ticket.amount %></td>
      <td class="center" style="vertical-align: middle"><%= ticket.sold %></td>
      <td class="center" style="vertical-align: middle">$<%= format_price ticket.flat_price(5) %></td>
      <td class="center" style="vertical-align: middle"><%= ticket.discount %>%</td>
      <td class="center" style="vertical-align: middle">
        <%= link_to mine_ticket_path(ticket) do %>
          <span class="glyphicon glyphicon-eye-open"></span>
        <% end %>
      </td>
      <td class="center" style="vertical-align: middle">
        <%= link_to edit_mine_ticket_path(ticket) do %>
          <span class="glyphicon glyphicon-pencil"></span>
        <% end -%>
      </td>
			<td class="center" style="vertical-align: middle">
        <%= link_to mine_ticket_path(ticket), method: :delete, data: { confirm: 'Are you sure you want to delete this listing?' } do %>
          <span class="glyphicon glyphicon-remove"></span>
        <% end -%>
      </td>
		</tr>
	<% end  %>
	</table>

app/views/mine/tickets/edit.html.erb
<div class='row' id='new-ticket'>
  <h1>Edit Listing</h1>
  <%= render 'form' %>
</div>

app/views/mine/tickets/index.html.erb
<div class="header">
  <ul class="nav nav-pills pull-right">
    <li><%= link_to 'New Listing', new_mine_ticket_path ,class: " btn-xs button"%></li>
  </ul>
  <h1 class="text-center league-gothic">Ticket Listings</h1>
</div>
<div class="ticket-lists table-responsive">
	<%= render 'table' %>
</div>
<%= paginate @tickets %>
<%= page_entries_info @tickets %>

app/views/mine/tickets/new.html.erb
<div class='row' id='new-ticket'>
  <h1>NEW TICKET LISTING</h1>
  <%= render 'form' %>
</div>

app/views/mine/tickets/show.html.erb
<div class='main clearfix purple-back row'>
  <h3 class='center'><%= @ticket.name %></h3>
  <div class='img-section col-lg-5'>
    <%= image_tag @ticket.image_url, class: 'ticket-image' %>
    <%= image_tag @ticket.sitting_map, class: 'ticket-image' %>
  </div>
  <div class='info-section col-lg-7'>
    <div class='info desc'>
      <div class='title'>City:</div>
      <div class='value'><%= @ticket.city %></div>
    </div>
    <div class='info desc'>
      <div class='title'>Category:</div>
      <div class='value'><%= @ticket.category_name %></div>
    </div>
    <div class='info desc'>
      <div class='title'>Desc:</div>
      <div class='value'><%= @ticket.desc %></div>
    </div>
    <div class='time info'>
      <div class='title'>Time:</div>
      <div class='value'><%= raw @ticket.time_range(:number) %></div>
    </div>
    <div class='info'>
      <div class='title'>Quantity:</div>
      <div class='value'><%= @ticket.amount %></div>
    </div>
    <div class='oprice info'>
      <div class='title'>Original Price:</div>
      <div class='value'><%= @ticket.oprice_to_currency %></div>
    </div>
    <div class='oprice info'>
      <div class='title'>Student discount:</div>
      <div class='value'><%= @ticket.student_discount %></div>
    </div>
    <div class='oprice info'>
      <div class='title'>Shipping Fee:</div>
      <div class='value'><%= @ticket.shipping_to_currency %></div>
    </div>
    <div class='oprice info'>
      <div class='title'>Will Call:</div>
      <div class='value'><%= @ticket.will_call %></div>
    </div>
    <% if @ticket.flatten_discount.present? %>
      <div class='group-price info'>
        <div class='title'>Flat price discount:</div>
        <div class="value">
          <%= @ticket.flatten_discount %>%
        </div>
      </div>
    <% else %>
      <div class='group-price info'>
        <div class='title'>Group Price:</div>
        <div class='value'>
          <%= link_to 'Add Group Price', new_mine_ticket_group_price_path(@ticket) %>
          <% @ticket.try(:ranked_group_prices).try(:each) do |gp| %>
            <p id='group-price-<%= gp.id %>'>
            <%= render_group_price gp %>  <%= link_to 'delete', [:mine, @ticket, gp], remote: true, method: 'DELETE' %>
            </p>
          <% end -%>
        </div>
      </div>
    <% end %>
    <div class="info">
      <%= link_to 'Edit', edit_mine_ticket_path(@ticket), class: "btn btn-primary" %>
      <%= link_to 'Back', mine_tickets_path, class: "btn btn-default" %>
    </div>
  </div>
</div>