config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "home#index"

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  get 'merchant/:id',  to: "profile#merchant", as: "merchant"
  get 'user/:id',      to: "profile#user",     as: "user"
  post 'merchant/:id/like', to: 'profile#like', as: 'like_merchant'
  get '/search',   to: "home#search",      as: :search
  get '/mobile_search', to: "home#mobile_search", as: :mobile_search
  get '/set_city', to: "home#set_city",    as: :set_city

  controller :static_page do
    get 'about', as: :about
    get 'terms', as: :terms
    get 'privacy', as: :privacy
  end

  resources :tickets do
    resources :groups do
      member do
        post :join_pay
      end
    end
    resources :orders
    member do
      post :like
      post :calc_price
    end
  end

  namespace :mine do
    resources :tickets do
      resources :group_prices
    end
    resource :wallet do
      post :recharge, :withdraw
    end

    get :profile, :edit_profile
    patch :profile, action: :update_profile

    resources :orders
  end
end

app/controllers/mine/group_prices_controller.rb
module Mine
  class GroupPricesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_ticket
    authorize_resource

    def new
      redirect_to root_path unless current_user.merchant?
    end

    def create
      @group_price = @ticket.group_prices.new(group_price_param)
      if @group_price.save
        redirect_to [:mine, @ticket], notice: 'Create Price Tier Success'
      else
        flash[:error] = @group_price.errors.full_messages.join(', ')
        render :new
      end
    end

    def destroy
      @group_price = GroupPrice.find(params[:id])
      @group_price.destroy
    end
 
    private

    def set_ticket
      @ticket = Ticket.find(params[:ticket_id])
    end

    def group_price_param
      params.require(:group_price).permit(:range_from, :range_to, :discount)
    end
  end
end

app/controllers/mine/orders_controller.rb
module Mine
  class OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_order, only: [:checkout, :show]
    authorize_resource

    def index
      if current_user.normal?
        @orders = current_user.orders.order(id: :desc).page(params[:page]).per_page(20)
      elsif !current_user.verification?
        render :text => "You need verification"
      elsif current_user.merchant?
        @orders = Order.merchant_orders(current_user.id).page(params[:page]).per_page(20)
      end
    end

    def show
    end
    
    def update
      #TODO: Deal with payment thing
    end

    private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:ticket_id, :count)
    end
    
  end
end

app/controllers/mine/tickets_controller.rb
module Mine
  class TicketsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_ticket, only: [:show, :edit, :update, :destroy]
    authorize_resource

    # GET /tickets
    def index
      @q = Ticket.ransack(params[:q])
      @tickets = @q.result.where(user_id: current_user.id).page(params[:page]).per_page(20)
    end

    # GET /tickets/1
    def show
    end

    # GET /tickets/new
    def new
      redirect_to user_session_path unless current_user && current_user.merchant?
      @ticket = Ticket.new
      @ticket.group_prices.build
    end

    # GET /tickets/1/edit
    def edit
    end

    # POST /tickets
    def create
      @ticket = current_user.tickets.new(ticket_params)
      if @ticket.save
        respond_to do |format|
          format.html { redirect_to [:mine, @ticket], notice: 'Ticket was successfully created.' }
          format.json { render json: @ticket }
        end
      else
        respond_to do |formant|
          format.html { render :new, notice: 'Faild to create new ticket, please try again.' }
          format.json { render json: { error_code: 0 } }
        end
      end
    rescue Exception => e
      @ticket = Ticket.new(ticket_params)
      flash[:error] = e.inspect
      render :new
    end

    # PATCH/PUT /tickets/1
    def update
      if @ticket.update(ticket_params)
        redirect_to [:mine, @ticket], notice: 'Ticket was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /tickets/1
    def destroy
      @ticket.destroy
      redirect_to mine_tickets_path, notice: 'Listing was successfully deleted.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = current_user.tickets.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      change_params_year_format params      
      params.require(:ticket).permit(
        :city,
        :category_id,
        :name,
        :desc, 
        :start_at,
        :end_at,
        :amount,
        :minimum_amount,
        :oprice,
        :flatten_discount,
        :flatten_price,
        :student_discount,
        :shipping,
        :will_call,
        :service_fee_waived,
        :image,
        :sitting_map,
        group_prices_attributes: [:range_from, :range_to, :price]
      )
    end

    def format_time time
      return "" if time.blank?
      time_ary = time.split("/")
      [time_ary[1], time_ary[0], time_ary[2]].join("/").try(:to_datetime).try(:to_s, :db)
    end

    def change_params_year_format params
      params[:ticket][:start_at] = format_time params[:ticket][:start_at]
      params[:ticket][:end_at] = format_time params[:ticket][:end_at]
      params
    end
  end

end

app/controllers/mine/wallets_controller.rb
module Mine
  class WalletsController < ApplicationController
    before_action :authenticate_user!
    authorize_resource class: false

    def show
    end

    def recharge
      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        card: params[:stripeToken]
      )

      @transaction = Transaction.new(dollar: transaction_param[:recharge],
                                     user: current_user,
                                     transaction_type: :recharge,
                                     token: params[:stripeToken],
                                     customer_id: customer.id)

      Stripe::Charge.create(
        customer: customer.id,
        amount: @transaction.dollar_in_cents,
        description: 'Recharge to GroupEt Account',
        currency: 'usd'
      )

      @transaction.status = :success
      @transaction.save!

      redirect_to mine_wallet_path, notice: 'Recharge Success'
    rescue Stripe::CardError => e
      redirect_to mine_wallet_path, error: e.message
    rescue ActiveRecord::RecordNotSaved
      redirect_to mine_wallet_path, error: @transaction.errors.full_messages.join(' ')
    end

    def withdraw
    end

    private

    def transaction_param
      params.permit!
    end
  end
end

app/controllers/mine_controller.rb
class MineController < ApplicationController
  before_action :authenticate_user!
  authorize_resource class: false

  def profile
    @favourite_tickets = current_user.favourites
  end

  def update_profile
    final_param = current_user.merchant? ? merchant_param : user_param

    if current_user.update(final_param)
      respond_to do |format|
        format.html { redirect_to action: :profile }
        format.mobile { redirect_to mine_edit_profile_path }
      end 
    else
      render :edit_profile
    end
  end
  
  def edit_profile
    if current_user.merchant?
      @merchant_info = current_user.merchant_info || MerchantInfo.new(user_id: current_user.id)
      @address = @merchant_info.address || @merchant_info.build_address
    else
      @user_info = current_user.user_info || UserInfo.new(user_id: current_user.id)
      @address = @user_info.address || @user_info.build_address
    end
  end

  private

  def merchant_param
    params.require(:user).permit(:name,
                                 :email,
                                 :avatar,
                                 merchant_info_attributes:
                                 [:latitude, :longitude,
                                  :category_id,
                                  :phone,
                                  :url,
                                  :workday_opening_time,
                                  :sat_opening_time,
                                  :sun_opening_time,
                                  :orgnization,
                                  :sales_email,
                                  :sales_phone,
                                  address_attributes: [:first,
                                                       :second,
                                                       :city,
                                                       :state,
                                                       :zipcode]
                                 ]
                               )
  end
  def user_param
    params.require(:user).permit(:name,
                                 :avatar,
                                 :email,
                                 user_info_attributes: [
                                   :zipcode,
                                   :phone,
                                   :group_name,
                                   :number_of_group_members,
                                   :university,
                                   :wallet_link,
                                   :billing_address,
                                   address_attributes: [:first,
                                                        :second,
                                                        :city,
                                                        :state,
                                                        :zipcode]
                                 ]
                                )
  end
end

app/helpers/mine/tickets_helper.rb
module Mine::TicketsHelper
  def title_sort_icon
    if @sort_by == 'title_down' 
      link_to mine_tickets_path(sort_by: :title_up) do
        content_tag(:span, nil, class: 'glyphicon glyphicon-chevron-down')
      end
    else
      link_to mine_tickets_path(sort_by: :title_down) do
        content_tag(:span, nil, class: 'glyphicon glyphicon-chevron-up')
      end
    end 
  end
end

app/views/mine/_merchant_profile_form.html.erb
<%= f.input :email, disabled: true, as: :email, input_html: { style: "color: #fffc00" } %>
<%= f.input :name %>
<%= f.input :avatar, as: :file %>
<%= f.simple_fields_for :merchant_info, @merchant_info do |form| %>
  <%= form.input :orgnization, required: true %>
  <%= form.association :category %>
  <%= form.input :workday_opening_time %>
  <%= form.input :sat_opening_time %>
  <%= form.input :sun_opening_time %>
  <%= form.input :url, as: :url %>
  <%= form.input :sales_phone, as: :tel %>
  <%= form.input :sales_email, required: true, as: :email %>
  Address:
  <%= form.simple_fields_for :address, @address do |addr_field| %>
    <%= addr_field.input :first, label: 'First Line' %>
    <%= addr_field.input :second, label: 'Second Line' %>
    <%= addr_field.input :city %>
    <%= addr_field.input :state %>
    <%= addr_field.input :zipcode %>
  <% end %>
<% end -%>

app/views/mine/_merchant_profile_form.mobile.slim
.ui-corner-all.custom-corners
  .ui-bar.ui-bar-a
    h3 Base Info
  .ui-body.ui-body-a
    = f.input :email, disabled: true, as: :email, label: false
    = f.input :name, label: false, placeholder: "Name" 
    = f.input :avatar, as: :file, label: false, placeholder: "Avatar" 
    = f.simple_fields_for :merchant_info, @merchant_info do |form| 
      = form.input :orgnization, required: true, label: false, placeholder: "Organization"
      = form.association :category, label: false, placeholder: "Categor"
      = form.input :workday_opening_time, label: false, placeholder: "Workday Opening Time"
      = form.input :sat_opening_time, label: false, placeholder: "Sat Opening Time" 
      = form.input :sun_opening_time, label: false, placeholder: "Sun Opening Time"
      = form.input :url, as: :url, label: false, placeholder: "Url"
      = form.input :sales_phone, as: :tel, label: false, placeholder: "Sales Phone" 
      = form.input :sales_email, required: true, as: :email, label: false, placeholder: "Sales Email" 
      label Address
      = form.simple_fields_for :address, @address do |addr_field| 
        = addr_field.input :first, label: false, placeholder: 'First Line'
        = addr_field.input :second, label: false, placeholder: 'Second Line'
        = addr_field.input :city, label: false, placeholder: "City"
        = addr_field.input :state, label: false, placeholder: "State" 
        = addr_field.input :zipcode, label: false, placeholder: "Zipcode" 

app/views/mine/_merchant_profile_table.html.erb
<div class='row'>
  <div class='col-md-4'>Name:</div>
  <div class='col-md-8'><%= current_user.name %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Email:</div>
  <div class='col-md-8'><%= current_user.email %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Orgnization Name:</div>
  <div class='col-md-8'><%= current_user.merchant_info.try(:orgnization) %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Genre:</div>
  <div class='col-md-8'><%= current_user.try(:merchant_info).try(:category).try(:name) %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Hours of Operation:</div>
  <div class='col-md-8'><%= current_user.try(:merchant_info).try(:workday_opening_time) %></div>
  <div class='col-md-8 col-md-offset-4'><%= current_user.try(:merchant_info).try(:sat_opening_time) %></div>
  <div class='col-md-8 col-md-offset-4'><%= current_user.try(:merchant_info).try(:sun_opening_time) %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Sales Manager Email:</div>
  <div class='col-md-8'><%= current_user.try(:merchant_info).try(:sales_email) %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Sales Manager Phone:</div>
  <div class='col-md-8'><%= current_user.try(:merchant_info).try(:sales_phone) %></div>
</div>

<div class='row'>
  <div class='col-md-4'>Address:</div>
  <div class='col-md-8'><%= current_user.try(:address) %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Avatar:</div>
  <div class='col-md-8 logo'><%= image_tag current_user.avatar_url, size: '60x60' %></div>
</div>

app/views/mine/_user_profile_form.html.erb
<%= f.input :avatar, as: :file %>
<%= f.input :email, disabled: true, input_html: { style: "color: #fffc00" }, as: :email %>
<%= f.input :name, required: false %>

<%= f.simple_fields_for :user_info, @user_info do |form| %>
  <%= form.input :phone, as: :tel %>
  <%= form.input :group_name, wrapper_html: false %>
  <%= form.input :number_of_group_members %>
  <%= form.input :university %>
  Address:
  <%= form.simple_fields_for :address, @address do |addr_field| %>
    <%= addr_field.input :first, label: 'First Line' %>
    <%= addr_field.input :second, label: 'Second Line' %>
    <%= addr_field.input :city %>
    <%= addr_field.input :state %>
    <%= addr_field.input :zipcode %>
  <% end %>
<% end  -%>

app/views/mine/_user_profile_form.mobile.slim
.ui-corner-all.custom-corners
  .ui-bar.ui-bar-a
    h3 Base Info
  .ui-body.ui-body-a
    = image_tag current_user.try(:avatar_url), size: '80x80'
    = f.input :email, disabled: true, label: false
    = f.input :name, required: true, label: false
    = f.input :avatar, as: :file, label: false
    = f.simple_fields_for :user_info, @user_info do |form|
      = form.input :phone, as: :tel, label: false, placeholder: "Phone"
      = form.input :group_name, label: false, placeholder: "Group Name"
      = form.input :number_of_group_members, label: false, placeholder: "group members number"
      = form.input :university, label: false, placeholder: "University"
      label Address
      = form.simple_fields_for :address, @address do |addr_field|
        = addr_field.input :first, label: false, placeholder: "First Line"
        = addr_field.input :second, label: false, placeholder: "Second Line"
        = addr_field.input :city, label: false, placeholder: "City"
        = addr_field.input :state, label: false, placeholder: "State"
        = addr_field.input :zipcode, label: false, placeholder: "Zipcode"

app/views/mine/_user_profile_table.html.erb
<div class='row'>
  <div class='col-md-4'>Name:</div>
  <div class='col-md-8'><%= current_user.name %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Email:</div>
  <div class='col-md-8'><%= current_user.email %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Phone:</div>
  <div class='col-md-8'><%= current_user.user_info.try(:phone) %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Group Name:</div>
  <div class='col-md-8'><%= current_user.user_info.try(:group_name) %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Number of Group members:</div>
  <div class='col-md-8'><%= current_user.user_info.try(:number_of_group_members) %></div>
</div>
<div class='row'>
  <div class='col-md-4'>University:</div>
  <div class='col-md-8'><%= current_user.user_info.try(:University) %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Address:</div>
  <div class='col-md-8'><%= current_user.try(:address) %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Wallet Url:</div>
  <div class='col-md-8'><%= current_user.user_info.try(:wallet_url) %></div>
</div>
<div class='row'>
  <div class='col-md-4'>Avatar:</div>
  <div class='col-md-8 logo'><%= image_tag current_user.avatar_url, size: '60x60' %></div>
</div>

app/views/mine/edit_profile.html.erb
<div id='edit-profile'>
	<h1>Edit Profile</h1>
	<hr/>
	<%= simple_form_for current_user, url: mine_profile_path, method: :patch, wrapper: :clean do |f| %>
    <!---TODO error doesnot display complete--->
    <% if current_user.errors.any? %>
      <div id="error_explanation">
        <div class="alert alert-danger" role='alert'>
          The form contains <%= pluralize(current_user.errors.count, "error") %>.
          <ul>
            <% current_user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>

	  <div class="row">
	    <div class="col-xs-12">
				<% if current_user.merchant? %>
				  <%= render partial: 'merchant_profile_form', locals: {f: f} %>
        <% else %>
          <%= render partial: 'user_profile_form', locals: {f: f} %>
		    <% end %>
	      <%= f.button :submit, 'Update Your Profile' %>
	    </div>
	  </div>
	<% end -%>
	
</div>
<%= javascript_include_tag 'web/form_validate' %>

app/views/mine/edit_profile.mobile.slim
- content_for :header do
  h1.title Profile
  = link_to "", root_path, class: "ui-btn ui-mini ui-icon-home ui-btn-icon-notext ui-corner-all ui-btn-left", data: {transition: "slidedown"}
  - if current_user
    = link_to "", "#userpanel", class: "ui-btn ui-mini ui-icon-user ui-btn-icon-notext ui-corner-all ui-btn-right", data: {transition: "slidefade"}

= simple_form_for current_user, url: mine_profile_path, method: :patch, html: {enctype: "multipart/form-data", data: {ajax: "false"}} do |f|
  - if current_user.merchant?
    = render partial: 'merchant_profile_form.mobile.slim', locals: {f: f}
  - else
    = render partial: 'user_profile_form.mobile.slim', locals: {f: f}

  = f.button :submit, 'Update'

- content_for :javascript
  javascript:
    $.mobile.navigate("#{mine_edit_profile_path}")

app/views/mine/profile.html.erb
<div class='col-lg-8 center-block profile' style='float:none'>
  <div class='panel panel-info detail'>

    <div class="light-purple-back">
      Profile
      <span class='pull-right'>
        <%= link_to profile_url do %>
          <span class='yellow glyphicon glyphicon-eye-open'></span>
        <% end %>

        <%= link_to mine_edit_profile_path do %>
          <span class='yellow glyphicon glyphicon-edit'>
        <% end %>
      </span>
    </div>

    <div class="panel-body">
      <% if current_user.merchant? %>
        <%= render 'merchant_profile_table' %>
      <% else %>
        <%= render 'user_profile_table' %>
      <% end %>
    </div>
  </div>
</div>

<% if @favourite_tickets.present? -%>
  <h2 class='center'>My Favorite Tickets</h2>
  <table class="table table-hover">
    <tbody>
      <% @favourite_tickets.each do |ticket| %>
        <tr>
          <td><%= link_to ticket.name, ticket %></td>
          <td><%= ticket.category_name %></td>
          <td><%= ticket.amount %></td>
          <td><%= ticket.oprice_to_currency %></td>
          <td><%= render_date ticket.start_at %></td>
          <td><%= link_to ticket.merchant_name, merchant_path(id: ticket.user_id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end -%>

app/views/mine/profile.mobile.slim
= content_for :header do
  h2.title Favorite Tickets
  = link_to "", root_path, class: "ui-btn ui-mini ui-icon-home ui-btn-icon-notext ui-corner-all ui-btn-left", data: {transition: "slidedown"}
  - if current_user
    = link_to "", "#userpanel", class: "ui-btn ui-mini ui-icon-user ui-btn-icon-notext ui-corner-all ui-btn-right", data: {transition: "slidefade"}

ul(data-role="listview" data-inset="true")
  - @favourite_tickets.each do |ticket|
    li
      = link_to ticket do
        = image_tag ticket.try(:image_url, :thumb)
        h3= ticket.name
        p= ticket.time_range(:word)
        p
          span Amount: 
          span= ticket.amount
        p
          span Price: 
          span= ticket.oprice_to_currency