config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root "home#index"

  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }

  get 'merchant/:id',  to: "profile#merchant", as: "merchant"
  get 'user/:id',      to: "profile#user",     as: "user"
  post 'merchant/:id/like', to: 'profile#like', as: 'like_merchant'
  get '/search',   to: "home#search",      as: :search
  get '/mobile_search', to: "home#mobile_search", as: :mobile_search
  get '/set_city', to: "home#set_city",    as: :set_city

  controller :static_page do
    get 'about', as: :about
    get 'terms', as: :terms
    get 'privacy', as: :privacy
  end

  resources :tickets do
    resources :groups do
      member do
        post :join_pay
      end
    end
    resources :orders
    member do
      post :like
      post :calc_price
    end
  end

  namespace :mine do
    resources :tickets do
      resources :group_prices
    end
    resource :wallet do
      post :recharge, :withdraw
    end

    get :profile, :edit_profile
    patch :profile, action: :update_profile

    resources :orders
  end
end

app/views/layouts/_change_city.html.erb
<div class="modal fade" id="change_city" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel" style='color: white;'>Set City</h4>
      </div>
      <div class="modal-body">
        <%= form_tag set_city_path, method: :get do %>
          <%= select_tag 'city', options_for_select(Ticket::CITIES, session_city), class: 'form-control' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" id='city_confirm'>Confirm</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_flash_messages.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= flash[:notice]  %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= flash[:error] %>
  </div>
<% end -%>

app/views/layouts/_footer.html.erb
<div class='footer'>
  <div class='container'>
    <div class='text-muted'>
      <div class='left'>
        <span class='purple'>CONTACT US: </span>
        <span>info@group-et.com</span>
      </div>
      <div class='right'>
        <span><a href='/terms'>TERMS OF SERVICE</a></span>
        <span><a href='privacy'>PRIVACY POLICY</a></span>
        <span><a href='/about#faq'>FAQ</a></span>
        <span><a href='/about'>ABOUT US</a></span>
      </div>
    </div>
    <div class="text-muted">
      <div class="right copyrights">
        <span>© 2015 GROUPET, LLC.</span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div id='header' class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header col-md-3">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <%= image_tag "logo.png", size: "200x73" %>
      </a>
    </div>
    <div class='navbar-nav navbar-search col-md-4'>
      <%= form_for TicketsSearch.new, url: search_path, method: :GET, html: { id: 'search', class: 'navbar-form'} do |f|  %>
        <%= f.text_field :query, placeholder: 'Quick Search' %>
        <span class='glyphicon glyphicon-search'></span>
      <% end -%>
    </div>
    <%- if current_user %>
      <ul class="nav navbar-nav navbar-right col-md-4" id="user">
        <div id="city">
          <span class='glyphicon glyphicon-map-marker'></span>
          <%= link_to session_city || 'Select Your City', "#", id: 'set_city', data: { toggle: "modal", target: "#change_city" } %>
        </div>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            Profile<span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li role="presentation">
            <% if can?(:manage, Ticket) %>
              <%= link_to 'Tickets', mine_tickets_path %>
            <% end %>
            <%= link_to 'Profile', mine_profile_path %>
            <%= link_to 'Wallet', mine_wallet_path %>
            <%= link_to 'Orders', mine_orders_path %>
            <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        </li>
        <li class='avatar'><%= image_tag current_user.avatar_url %></li>
      </ul>
    <% else %>
      <div class="navbar-right col-md-4">
        <div id="city">
          <span class='glyphicon glyphicon-map-marker'></span>
          <%= link_to session_city || 'Select Your City', "#", id: 'set_city', data: { toggle: "modal", target: "#change_city" } %>
        </div>
        <ul id="user">
          <li><%= link_to "Join", new_user_registration_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_user_panel.mobile.slim
#userpanel data={role: "panel", position: 'right', display: 'overlay', theme: 'b'}
  ul data={role: "listview"}
    /li= link_to 'Tickets', mine_orders_path if can?(:manage, Ticket)
    li= link_to 'Profile', mine_edit_profile_path
    li= link_to 'Favorite', mine_profile_path
    /li= link_to 'Wallet', mine_wallet_path
    li= link_to 'Orders', mine_orders_path
    li= button_to 'Log out', destroy_user_session_path, method: :delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupEt</title>
    <%= content_for :social_share %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/header' %>
    <div id="wrap">
      <%= render 'layouts/change_city' %>
      <%= render 'layouts/flash_messages' %>
      <%= render 'home/topbar' %>
      <div class='container' id='body-container'>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/layouts/application.mobile.slim
doctype html
html
  head
    meta charset="utf-8"
    title GroupEt
    meta content="initial-scale=1, maximum-scale=1" name="viewport"
    = stylesheet_link_tag "application_mobile"
    = javascript_include_tag "application_mobile"
    = csrf_meta_tags 
  body
    div(data={role: "page"})
      = render "layouts/user_panel" if current_user
      header(data={role: "header", position: "fixed"})
        = content_for :header
      div(data={role: "content"})
        = yield
      footer(data={role: "footer", position: "fixed"})
        = content_for :footer
      = content_for :javascript